### ISSUE TITLE
how to implement in postgresql?

### ISSUE THREAD

**Issue by sla-te** [boxboat/fixuid#17]
Hi, im trying to implement this in a custom postgres image

### Dockerfile
```
FROM postgres:latest
RUN addgroup --gid 1000 docker && \
    adduser --uid 1000 --ingroup docker --home /home/docker --shell /bin/sh --disabled-password --gecos "" docker

RUN USER=docker && GROUP=docker && \
    apt-get update -y && \
    apt-get install curl -y && \
    apt-get clean -y && \
    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4/fixuid-0.4-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml
ENTRYPOINT ["fixuid"]

RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG de_DE.utf8
USER docker:docker
```

### docker-compose.yml
```
 postgres:
    build:
      ./pgsql
    restart: always
    container_name: postgres
    user: "${PUID}:${PGID}"
    hostname: pgsql-01
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/conf:/config
```
When I do docker-compose up docker-compose.yml it seems to just repeatedly execute fixuid but postgres never starts. This is just a wild guess, but maybe this fails because I override the entrypoint of the postgres image?

In the official docs for postgres docker I found that extending the image works by writing a simple Dockerfile like so:
```
FROM postgres:9.4
RUN localedef -i de_DE -c -f UTF-8 -A /usr/share/locale/locale.alias de_DE.UTF-8
ENV LANG de_DE.utf8
````
That works just fine.

**Comment by caleblloyd** [comment]
Postgresql already sets up a user and group

So if you want to use fixuid no need to add a `docker:docker` just configure fixuid to change to `postgres:postgres`

Also yes you need their entry point so in your image put

`ENTRYPOINT ["fixuid", "docker-entrypoint.sh"]`

**Comment by sla-te** [comment]
Hmm now I get `/bin/sh: 1: ENTRYPOINT: not found`. I also found postgresql's Dockerfile [](https://github.com/docker-library/postgres/blob/42f9ab3bab65fdbabbf35130c68a9869b6e82ee7/11/Dockerfile) and its really named docker-entrypoint.sh

**Comment by caleblloyd** [comment]
If all you are trying to do is persist your database data to disk, you can just use a named volume in compose, you don't need fixuid:

```
volumes:
  db-data:

services:
  db:
    image: postgres:11-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
```

**Comment by caleblloyd** [comment]
There's even a postgres example here: https://docs.docker.com/compose/compose-file/#volumes

**Comment by sla-te** [comment]
Im trying to achieve that the bind mounted folder doesn't have root as owner on the host. Sure manually it can be fixed with chown -R 1000:1000 ./thatfolder on the but Id prefer to have it automated.

I just want to be able to quickly view all the files postgres is generating from inside the IDE and handling/viewing the files inside a docker volume is not as enjoyable.

**Comment by chwba** [comment]
I just want to be able to quickly view all the files postgres is generating inside the IDE and handling the files inside a docker volume is not as enjoyable :)

**Comment by caleblloyd** [comment]
Dockerfile:

```
FROM postgres:10.4-alpine

RUN apk add --no-cache curl

RUN USER=postgres && GROUP=postgres && \
    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4/fixuid-0.4-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml

USER postgres:postgres
ENTRYPOINT ["fixuid", "docker-entrypoint.sh"]
CMD ["postgres"]
```

docker-compose.yml:
```
version: '3.4'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    user: "${PUID:-1000}:${PGID:-1000}"
    volumes:
      - ./database/data:/var/lib/postgresql/data
```

start up:
```
export PUID=$(id -u)
export PGID=$(id -g)
docker-compose up --build
```

**Comment by caleblloyd** [comment]
Note that you need to pre-create `./database/data` on your system. You can put a `.gitignore` in there:

```
*
!.gitignore
```

**Comment by sla-te** [comment]
Thank you very much for your efforts. Any special reason u used 10.4 alpine or could i also simply use latest?

**Comment by caleblloyd** [comment]
It'll work with any Alpine tag

**Comment by sla-te** [comment]
I tried to run it like that and now I get:

```
initdb: could not change permissions of directory "/var/lib/postgresql/data": Operation not permitted
fixing permissions on existing directory /var/lib/postgresql/data ... 
```

and the container hangs in a restart-loop, am I missing something?

**Comment by sla-te** [comment]
### docker-compose
```
  db:
    build:
      context: ./
      dockerfile: PGSQLDockerfile
    restart: always
    container_name: pgsql-01
    user: "${PUID}:${PGID}"
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./pgsql-01/data:/var/lib/postgresql/data
      - ./pgsql-01/conf:/config
 ```

### .env
```
POSTGRES_USER=user
POSTGRES_PASSWORD=pw
POSTGRES_DB=db
PUID=1000
PGID=1000
```

### PGSQLDockerfile
```
FROM postgres:10.4-alpine

RUN apk add --no-cache curl

RUN USER=postgres && GROUP=postgres && \
    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4/fixuid-0.4-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml

USER postgres:postgres
ENTRYPOINT ["fixuid", "docker-entrypoint.sh"]
CMD ["postgres"]
```
