### ISSUE TITLE
Doesn't work for named volumes

### ISSUE THREAD

**Issue by thatnerdjosh** [boxboat/fixuid#8]
Hello, it seems that when I mount a volume via the filesystem it properly sets perms, however when it is a named volume it doesn't. See below that /var/lib/whoosh is owned by 1000:1000 still

Thanks!

```
    volumes:
      - .:/usr/src/app
      - core-woosh:/var/lib/whoosh
    stdin_open: true
    tty: true

volumes:
  core-postgres-volume:
  core-woosh:
```

```
appuser@555c1718485c:/var/lib$ ls -alh | grep whoosh
drwxr-xr-x.  2 1000 1000    6 Mar 15 17:53 whoosh
```

```
appuser@555c1718485c:~$ ls -alh | head -n 2
total 132K
drwxrwxr-x. 16 appuser appuser 4.0K Mar 15 17:58 .
```
